server:
  port: 9999
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.210:3306/postal?serverTimezone=UTC
    username: diablogus
    password: Co0lgu566g@1983
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

